name: Trigger Netlify Build
on:
  schedule:
    - cron: '0 0 * * *' # Once a day
jobs:
  build:
    name: Request Netlify Webhook
    runs-on: ubuntu-latest
    steps:
      - name: POST to Build Hook
        run: curl -X POST -d {} https://api.netlify.com/build_hooks/6174591fb25196f96c6c8bd7
